#!/bin/bash

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# detect tabs
for file in `git diff --cached --name-only --diff-filter=ACMR $against | egrep '(\.(hx|md|sh|hxml)$)'`; do
  git diff -U0 --cached -- "$file" | grep "^+.*	" && echo "Tabs detected in \"$file\", aborting commit" && exit 1
done

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
